# Generated by Django 5.2.8 on 2025-11-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["accommodation", "start_date", "end_date"],
                name="bookings_accommo_32d1c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booker", "created_at"], name="bookings_booker__893066_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "start_date"], name="bookings_status_f0ab31_idx"
            ),
        ),
    ]
